# Generated by Django 2.2.4 on 2019-09-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_service_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='skill')),
            ],
        ),
    ]
