# Generated by Django 2.2.4 on 2019-09-06 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skill', '0004_auto_20190904_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sended', models.BooleanField(default=False, verbose_name='Shipping flag')),
                ('stripe_id', models.CharField(max_length=200, verbose_name='Purchase_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skill.Service', verbose_name='Purchase Service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Purchase User')),
            ],
        ),
    ]
