# Generated by Django 2.2.4 on 2019-09-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0006_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='favorite_num',
            field=models.IntegerField(default=0),
        ),
    ]
