# Generated by Django 2.2.4 on 2019-09-24 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skill', '0007_service_favorite_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='favorited_user',
            field=models.ManyToManyField(related_name='favorite_services', to=settings.AUTH_USER_MODEL),
        ),
    ]
