# Generated by Django 2.2.4 on 2019-09-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0008_service_favorited_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
