# Generated by Django 2.2.4 on 2019-09-29 05:40

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0010_remove_service_favorite_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=stdimage.models.StdImageField(null=True, upload_to='photo'),
        ),
    ]
