# Generated by Django 2.2.4 on 2019-09-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0012_auto_20190929_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=7),
        ),
    ]
