# Generated by Django 2.2.4 on 2019-09-29 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0013_auto_20190929_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=7, validators=[django.core.validators.MinValueValidator(50.0), django.core.validators.MaxValueValidator(99999.0)]),
        ),
    ]
