# Generated by Django 2.2.4 on 2019-10-03 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0014_auto_20190929_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(default=50.0, validators=[django.core.validators.MinValueValidator(50.0), django.core.validators.MaxValueValidator(99999.0)]),
        ),
    ]
