# Generated by Django 2.2.4 on 2019-10-03 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0016_auto_20191003_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(default=5000, validators=[django.core.validators.MinValueValidator(5000), django.core.validators.MaxValueValidator(10000000)]),
        ),
    ]
